baseURL = "https://zr.github.io"
languageCode = "en-us"
title = "Hey, I'm Komatsu."
theme = "hermit"
disableKinds = ["RSS"]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "Komatsu Homepage."
  homeSubtitle = "Web Developer."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">zr All Rights Reserved.</a>'

  justifyContent = false
  relatedPosts = false
  code_copy_button = true
  
  # Add custom css
  customCSS = ["css/add.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/zr"

  [[params.social]]
    name = "qiita"
    url = "https://qiita.com/zr_"

  [[params.social]]
    name = "wantedly"
    url = "https://www.wantedly.com/secret_profiles/RhS5zndhKcNpSRcMKryx-LHTty-FlgMg"
